---
output: github_document
number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h1 align="center">floodGAM datasets</h1>

## Overview
As part of the floodGAM analysis, we developed a flood dataset focused on sub-daily sampling frequency for flood frequency analysis using annual maximum data. It includes 259 stations, each with at least 20 years of total data and at least 11 years of sub-daily data.

The stations are based on NVE-rapport 2016:85 [Flomdata: utvalg og kvalitetssikring av flomdata for flomfrekvensanalyser](https://asp.bibliotekservice.no/nve/title.aspx?tkey=23147), with added requirements for sub-daily sampling frequency around annual maxima and data up to 2023. 
 

## Dataprodukter

### Flomdata fra vannføringsstasjoner

 - download the set of annual maxima [l/s/km2] here.

The full streamflow time series for each station is available on the NVE server at (link). Database commands for pulling data from HYDRA II are in this repository at (link), along with a how-to guide at (link). All code for cleaning and quality control of raw streamflow data is available (here).

### Felt egenskaper

 - Fysiografiske og klimatiske feltegenskaper for de 259 stasjonene 

 - README for feltegenskaper 


### Andre dataprodukter

We also store other datasets relevant to the floodGAM analysis in this repository. The raw-data folder contains the list of station names, version numbers, and manually controlled utelatt years and stations used to make the database commands. The how-to folder contains guides describing how to get raw streamflow data. The Rdata folder saves many intermediate data objects used in the analysis. 


## Kvalitetskontroll av vannføringsdata

### Manuell fjerning

Rapporten 2016:85 identifiserer visse år med data som bør utelates for flomfrekvensanalyse. I tillegg har vi identifisert noen år og stasjoner som bør utelates hvis vi trenger fin tidsoppløsning.

 - `utelatt.csv` - list over år og stasjoner som utelates
 - `utelatt_notes.xlsx` - noen notater om manuelle fjernet år


### Håndtering av år med manglende data

NVE har ingen «perfekt» arkiv for verken findata eller døgndata. Noen arkiver er isredusert, mens andre er ikke. Det samme gjelder kompletthet. 

Vi bruker data fra arkiv HYKALP-ICECORR (arkiv 35), som har primærtkontrollerte data med fin/variabel tidsoppløsning og er virtuelt isreduserte. HYKVALP-ICECORR er ikke sekundærkontrollert eller kompletterte. 

Fordi HYKVAL-dataene ikke er komplette, må vi derfor ta beslutninger om hvordan vi skal håndtere år med manglende data. Vi velger å kryssjekke HYKVALP-ICECORR dataene med data fra et annet arkiv, HYDAG (arkiv 05), som inneholder kontrollerte, kompletterte døgndata som er isredusert og etterkontrollert. 

### Enforce findata and record length minimums


